import React from "react";
import Head from "next/head";
import AppMain from "@/components/Page/AppMain";
import type { AppProps } from "next/app";
import "@/style/main.scss";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Healthy Food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/logo/logo-no-background-short.svg" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;1,100;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <AppMain>
        <Component {...pageProps} />
      </AppMain>
    </>
  );
}
