import React from "react";
import Head from "next/head";
import AppMain from "@/components/Page/AppMain";
import type { AppProps } from "next/app";
import 'nprogress/nprogress.css';
import "react-quill/dist/quill.snow.css";
import "@/style/main.scss";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Healthy Food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/logo/logo-no-background-short.svg" />
      </Head>

      <AppMain>
        <Component {...pageProps} />
      </AppMain>
    </>
  );
}
